# Generated by Django 3.0.3 on 2020-02-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=150)),
                ('draw_weight', models.FloatField()),
                ('brace_height_inches', models.FloatField()),
                ('ata_distance_inches', models.FloatField()),
                ('cable_material', models.CharField(max_length=50)),
                ('stabalizer_setup', models.TextField()),
                ('rest_type', models.CharField(choices=[('BL', 'Blade'), ('DA', 'Drop Away'), ('WB', 'Whicker-Biscuit')], default='BL', max_length=2)),
                ('setup_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry_date', models.DateField()),
                ('log_notes', models.CharField(max_length=255)),
                ('bow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.Bow')),
            ],
        ),
    ]
