# Generated by Django 3.0.3 on 2020-02-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='name',
            field=models.CharField(default='empty name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bow',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bow',
            name='ata_distance_inches',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='brace_height_inches',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='cable_material',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='rest_type',
            field=models.CharField(choices=[('BL', 'Blade'), ('DA', 'Drop Away'), ('WB', 'Whicker-Biscuit')], default='BL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='setup_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='stabalizer_setup',
            field=models.TextField(null=True),
        ),
    ]
