# Generated by Django 3.0.3 on 2020-02-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_auto_20200223_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='picture',
            field=models.BinaryField(null=True),
        ),
    ]
