# Generated by Django 3.0.3 on 2020-02-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_accountprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scorecard.AccountProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scorecard.AccountProfile'),
            preserve_default=False,
        ),
    ]
