# Generated by Django 3.0.3 on 2020-02-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_auto_20200227_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='bow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scorecard.Bow'),
            preserve_default=False,
        ),
    ]
