# Generated by Django 3.0.3 on 2020-03-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0008_bow_picture_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('end_count', models.IntegerField()),
                ('shots_per_end', models.IntegerField()),
                ('max_score_per_show', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.LogEntry')),
                ('round_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.RoundType')),
            ],
        ),
    ]
