# Generated by Django 3.0.3 on 2020-03-06 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0010_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='bow',
            name='bow_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scorecard.BowType'),
        ),
    ]
